#PBS -lwalltime=00:05:00  
#PBS -lnodes=1:ppn=16     
                         # 1 node for this job
#PBS -S /bin/bash
#PBS -e /home/mckeuken/projects/post_mortem/logs/
#PBS -o /home/mckeuken/projects/post_mortem/logs/
n=`wc -l < $PBS_NODEFILE`
echo start of job in directory $PBS_O_WORKDIR
echo number of nodes is $n
echo the allocated nodes are:
cat $PBS_NODEFILE
echo starting working on problem $PBS_ARRAYID1

module load python
python /home/mckeuken/projects/post_mortem/fit_ml_cv_all_intensity_and_gradient_2D_fwhm12.py
